# Generated by Django 3.1 on 2021-07-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20210618_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='googlemaps',
            new_name='googlemaps_link',
        ),
    ]
