# Generated by Django 3.1 on 2021-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20210703_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(max_length=200, upload_to='uploads/2021'),
        ),
    ]
