# Generated by Django 3.1 on 2021-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20210716_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(max_length=200, upload_to='media/'),
        ),
    ]
